USE FACEOFF;

CREATE TABLE `USER` (
  `UID` char(32) NOT NULL,
  `NAME` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `IMG` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `KNOWNFACE` (
  `KID` int(11) NOT NULL AUTO_INCREMENT,
  `FNAME` varchar(45) DEFAULT NULL,
  `IMG` varchar(100) DEFAULT NULL,
  `UID` char(32) DEFAULT NULL,
  PRIMARY KEY (`KID`),
  KEY `KNOWNFACE_UID_98d30b12_fk_USER_UID` (`UID`),
  CONSTRAINT `KNOWNFACE_UID_98d30b12_fk_USER_UID` FOREIGN KEY (`UID`) REFERENCES `USER` (`UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `FACES` (
  `FID` int(11) NOT NULL AUTO_INCREMENT,
  `IMG` varchar(100) DEFAULT NULL,
  `KID` int(11) DEFAULT NULL,
  PRIMARY KEY (`FID`),
  KEY `FACES_KID_a823a5a3_fk_KNOWNFACE_KID` (`KID`),
  CONSTRAINT `FACES_KID_a823a5a3_fk_KNOWNFACE_KID` FOREIGN KEY (`KID`) REFERENCES `KNOWNFACE` (`KID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `STICKER` (
  `SID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `IMG` varchar(100) DEFAULT NULL,
  `UID` char(32) DEFAULT NULL,
  PRIMARY KEY (`SID`),
  KEY `STICKER_UID_281f58ae_fk_USER_UID` (`UID`),
  CONSTRAINT `STICKER_UID_281f58ae_fk_USER_UID` FOREIGN KEY (`UID`) REFERENCES `USER` (`UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


