# Generated by Django 3.1.2 on 2020-10-29 06:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(db_column='UID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=45, null=True)),
                ('img', models.CharField(blank=True, db_column='IMG', max_length=100, null=True)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('sid', models.AutoField(db_column='SID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=45, null=True)),
                ('img', models.CharField(blank=True, db_column='IMG', max_length=100, null=True)),
                ('uid', models.ForeignKey(blank=True, db_column='UID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'STICKER',
            },
        ),
        migrations.CreateModel(
            name='Knownface',
            fields=[
                ('kid', models.AutoField(db_column='KID', primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='FNAME', max_length=45, null=True)),
                ('img', models.CharField(blank=True, db_column='IMG', max_length=100, null=True)),
                ('uid', models.ForeignKey(blank=True, db_column='UID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'KNOWNFACE',
            },
        ),
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('fid', models.AutoField(db_column='FID', primary_key=True, serialize=False)),
                ('img', models.CharField(blank=True, db_column='IMG', max_length=100, null=True)),
                ('kid', models.ForeignKey(blank=True, db_column='KID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.knownface')),
            ],
            options={
                'db_table': 'FACES',
            },
        ),
    ]
