# Generated by Django 3.1.2 on 2020-11-03 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='faces',
            name='uid',
            field=models.ForeignKey(blank=True, db_column='UID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
    ]
